In [37]:
## Importing Essentials 
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt
import datetime
import w2_unittest
print(f"Last Updated: {datetime.datetime.now()}")

Last Updated: 2026-03-07 10:58:39.486219


### Systems of Linear Equations and Corresponding Numpy Arrays

#### Equation
$$
\begin {cases}
2x1 - x2 + x3 + x4 = 6, \\
x1 + 2x2 - x3 - x4 =3, \\
-x1 + 2x2 + 2x3 + 2x4 = 14, \\
x1 - x2 + 2x3 + x4 = 8
\end {cases}
$$

In [38]:
## Constructing A and b
A = np.array([[2,-1,1,1],[1,2,-1,-1],[-1,2,2,2],[1,-1,2,1]],dtype = np.dtype(int))
b = np.array([6,3,14,8],dtype = np.dtype(int))

In [39]:
w2_unittest.test_matrix(A,b)

 All tests passed


### Solution of Equation using Linear Algebra Package 

In [40]:
# Determinant of matrix A 
det_A = np.linalg.det(A)
x = np.linalg.solve(A,b)
print(f"Determinant of the matrix A is: {det_A:.2f}, Solution Vector is: {x}")

Determinant of the matrix A is: -17.00, Solution Vector is: [2. 3. 4. 1.]


In [41]:
w2_unittest.test_det_and_solution_scipy(det_A,x)

 All tests passed


### Elementary operations and Row Reductions
Elementary operations can be done by three simple steps 
* Multiply any row by non-zero number
* Add two rows and exchange one of the original rows with the result of the addition
* Swapping rows

* *In order to perform these operations we need to create three functions that will be used frequently to solve the Linear Equation*
*  **multiplyrows, addrows, swaprows**

In [42]:
def multiplyrows(matrix,row_index,multiplier): 
    new_matrix = matrix.copy()
    new_matrix[row_index] = new_matrix[row_index] * multiplier
    return new_matrix

In [43]:
def addrows(matrix,row_num_one,multiplier,row_num_two):
    new_matrix = matrix.copy()
    new_matrix[row_num_two] = new_matrix[row_num_one] * multiplier + new_matrix[row_num_two]
    return new_matrix

In [44]:
def swaprows(matrix,row_num_one,row_num_two):
    new_matrix = matrix.copy()
    new_matrix[[row_num_one,row_num_two]] = new_matrix[[row_num_two,row_num_one]]
    return new_matrix

### Testing 

In [45]:
A

array([[ 2, -1,  1,  1],
       [ 1,  2, -1, -1],
       [-1,  2,  2,  2],
       [ 1, -1,  2,  1]])

In [46]:
A_copy = np.array([[2,-1,1,1],[1,2,-1,-1],[-1,2,2,2],[1,-1,2,1]],dtype = np.dtype(int))
print(f"Original Matrix: {A}")
print(f"Original Matrix after its third row multiplied by -2: {multiplyrows(A_copy,2,-2)}")

Original Matrix: [[ 2 -1  1  1]
 [ 1  2 -1 -1]
 [-1  2  2  2]
 [ 1 -1  2  1]]
Original Matrix after its third row multiplied by -2: [[ 2 -1  1  1]
 [ 1  2 -1 -1]
 [ 2 -4 -4 -4]
 [ 1 -1  2  1]]


In [10]:
print(f"Original Matrix: {A}")
print(f"Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4: {addrows(A_copy,1,4,2)}")

Original Matrix: [[ 2 -1  1  1]
 [ 1  2 -1 -1]
 [-1  2  2  2]
 [ 1 -1  2  1]]
Original matrix after exchange of the third row with the sum of itself and first row multiplied by 4: [[ 2 -1  1  1]
 [ 1  2 -1 -1]
 [ 3 10 -2 -2]
 [ 1 -1  2  1]]


In [11]:
print(f"Original Matrix: {A}")
print(f"Original matrix after swapping very first and last rows: {swaprows(A_copy,0,3)}")

Original Matrix: [[ 2 -1  1  1]
 [ 1  2 -1 -1]
 [-1  2  2  2]
 [ 1 -1  2  1]]
Original matrix after swapping very first and last rows: [[ 1 -1  2  1]
 [ 1  2 -1 -1]
 [-1  2  2  2]
 [ 2 -1  1  1]]


In [12]:
 # stack horizontally matrix A and vector b, which needs to be reshaped as a vector (4, 1)
b = b.reshape(4,1)
A_system = np.hstack((A,b))
A_system

array([[ 2, -1,  1,  1,  6],
       [ 1,  2, -1, -1,  3],
       [-1,  2,  2,  2, 14],
       [ 1, -1,  2,  1,  8]])

In [13]:
# swap row 0 and row 1 of matrix A_system (remember that indexing in NumPy array starts from 0)
A_ref = swaprows(A_system,0,1)
A_ref

array([[ 1,  2, -1, -1,  3],
       [ 2, -1,  1,  1,  6],
       [-1,  2,  2,  2, 14],
       [ 1, -1,  2,  1,  8]])

In [14]:
# multiply row 0 of the new matrix A_ref by -2 and add it to the row 1
A_ref = addrows(A_system,0,-2,1)
A_ref

array([[ 2, -1,  1,  1,  6],
       [-3,  4, -3, -3, -9],
       [-1,  2,  2,  2, 14],
       [ 1, -1,  2,  1,  8]])

In [15]:
# multiply row 0 of the new matrix A_ref by -2 
A_ref = multiplyrows(A_system,0,-2)
A_ref

array([[ -4,   2,  -2,  -2, -12],
       [  1,   2,  -1,  -1,   3],
       [ -1,   2,   2,   2,  14],
       [  1,  -1,   2,   1,   8]])

### Solution for the System of Equations using Row Reduction

In [16]:
A_system

array([[ 2, -1,  1,  1,  6],
       [ 1,  2, -1, -1,  3],
       [-1,  2,  2,  2, 14],
       [ 1, -1,  2,  1,  8]])