In [15]:
# Importing Libraries
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt 
import datetime
print(f"Last Updated:{datetime.datetime.now()}")

Last Updated:2026-02-17 14:31:40.894491


# Solving Linear Systems: 3 Variables

## Representing and Solving a system of Linear Equations using Matrices

#### System of Linear System with three equaiton and three unknown variables. 
$$
\begin{cases}
4x_1 - 3x_2 + x_3 = -10, \\
2x_1 + x_2 + 3x_3 = 0, \\
-x_1 + 2x_2 - 5x_3 = 17
\end{cases}
$$

In [16]:
## Seperating Co-effieciant and Values 
A = np.array([[4,-3,1],[2,1,3],[-1,2,-5]])
B = np.array([-10,0,17])

In [17]:
print(f"Matrix A: {A},  Matrix B:{B}")

Matrix A: [[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]],  Matrix B:[-10   0  17]


In [18]:
A.shape,B.shape

((3, 3), (3,))

In [19]:
x = np.linalg.solve(A,B)
print(f"Solution: {x}")

Solution: [ 1.  4. -2.]


In [20]:
## Evaluating the determinant of The Matrix 

det_a = np.linalg.det(A)
print(f"Determinant of matrix A is : {det_a:.2f}")   

## Value is non zero thats why it has value of real number

Determinant of matrix A is : -60.00


## Solving system of Linear Equations using Row Reduction 
#### Functions for Elementary Operations 
#### Let's review *elementary oprations*, which don't change the solution set of a linear system: 
* Multiply any row by a non-zero number
* Add two rows and exchange one of the original rows with the result of the addition
* Swap rows
#### In the case of larger systems you will need to apply elementary operations multiple time,
#### Thus it's convenient to define the correspoding pyhton functions.
#### Investigate them in the following code cells with the example

In [21]:
## Preperation for Row Reduction ------
# Reshaping B 
B = B.reshape(3,1)
## Unifying 
aug_mat = np.hstack((A,B))
aug_mat

array([[  4,  -3,   1, -10],
       [  2,   1,   3,   0],
       [ -1,   2,  -5,  17]])

In [31]:
## Multiplying any row by a non zero number 
def multiplyrow(matrix,row_index,multiplier):
    
    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[row_index] = matrix_new[row_index] * multiplier

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after multiplying third row by 2 : {multiplyrow(aug_mat,2,2)}")


Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after multiplying third row by 2 : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -2   4 -10  34]]


In [32]:
## Add two rows and exchange one of the original rows with the result of the addition
def addrow(matrix,row_index_first,row_index_second,multiplier):
    
    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[row_index_second] = matrix_new[row_index_first] * multiplier + matrix_new[row_index_second]

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after adding two rows and exchange one of the original rows : {addrow(aug_mat,1,2,1/2)}")
 

Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after adding two rows and exchange one of the original rows : [[  4  -3   1 -10]
 [  2   1   3   0]
 [  0   2  -3  17]]


In [33]:
# exchange row_index_first and row_index_second of the matrix M
def swaprows(matrix,row_index_first,row_index_second): 

    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[[row_index_first,row_index_second]] = matrix_new[[row_index_second,row_index_first]]

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after swapping first and 3 rows: {swaprows(aug_mat,0,2)}")

Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after swapping first and 3 rows: [[ -1   2  -5  17]
 [  2   1   3   0]
 [  4  -3   1 -10]]
