In [18]:
# Importing Libraries
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt 
import datetime
print(f"Last Updated:{datetime.datetime.now()}")

Last Updated:2026-02-20 06:36:22.522159


# Solving Linear Systems: 3 Variables

## Representing and Solving a system of Linear Equations using Matrices

#### System of Linear System with three equaiton and three unknown variables. 
$$
\begin{cases}
4x_1 - 3x_2 + x_3 = -10, \\
2x_1 + x_2 + 3x_3 = 0, \\
-x_1 + 2x_2 - 5x_3 = 17
\end{cases}
$$

In [19]:
## Seperating Co-effieciant and Values 
A = np.array([[4,-3,1],[2,1,3],[-1,2,-5]])
B = np.array([-10,0,17])

In [20]:
print(f"Matrix A: {A},  Matrix B:{B}")

Matrix A: [[ 4 -3  1]
 [ 2  1  3]
 [-1  2 -5]],  Matrix B:[-10   0  17]


In [21]:
A.shape,B.shape

((3, 3), (3,))

In [22]:
## Evaluating the determinant of The Matrix 

det_a = np.linalg.det(A)
print(f"Determinant of matrix A is : {det_a:.2f}")   

## Value is non zero thats why it has value of real number

Determinant of matrix A is : -60.00


## Solving system of Linear Equations using Row Reduction 
#### Functions for Elementary Operations 
#### Let's review *elementary oprations*, which don't change the solution set of a linear system: 
* Multiply any row by a non-zero number
* Add two rows and exchange one of the original rows with the result of the addition
* Swap rows
#### In the case of larger systems you will need to apply elementary operations multiple time,
#### Thus it's convenient to define the correspoding pyhton functions.
#### Investigate them in the following code cells with the example

In [23]:
## Preperation for Row Reduction ------
# Reshaping B 
B = B.reshape(3,1)
## Unifying 
aug_mat = np.hstack((A,B))
aug_mat

array([[  4,  -3,   1, -10],
       [  2,   1,   3,   0],
       [ -1,   2,  -5,  17]])

In [24]:
## Multiplying any row by a non zero number 
def multiplyrow(matrix,row_index,multiplier):
    
    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[row_index] = matrix_new[row_index] * multiplier

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after multiplying third row by 2 : {multiplyrow(aug_mat,2,2)}")


Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after multiplying third row by 2 : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -2   4 -10  34]]


In [25]:
## Add two rows and exchange one of the original rows with the result of the addition
def addrow(matrix,row_index_first,multiplier,row_index_second,):
    
    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[row_index_second] = matrix_new[row_index_first] * multiplier + matrix_new[row_index_second]

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after adding two rows and exchange one of the original rows : {addrow(aug_mat,1,1/2,2)}")
 

Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after adding two rows and exchange one of the original rows : [[  4  -3   1 -10]
 [  2   1   3   0]
 [  0   2  -3  17]]


In [26]:
# exchange row_index_first and row_index_second of the matrix M
def swaprows(matrix,row_index_first,row_index_second): 

    ## Copy of main matrix 
    matrix_new = matrix.copy()

    ## Main Equation 
    matrix_new[[row_index_first,row_index_second]] = matrix_new[[row_index_second,row_index_first]]

    return matrix_new

print(f"Prime Matrix : {aug_mat}")
print(f"Prime Matrix after swapping first and 3 rows: {swaprows(aug_mat,0,2)}")

Prime Matrix : [[  4  -3   1 -10]
 [  2   1   3   0]
 [ -1   2  -5  17]]
Prime Matrix after swapping first and 3 rows: [[ -1   2  -5  17]
 [  2   1   3   0]
 [  4  -3   1 -10]]


## Row Reduction and Solution of the Linear System 
#### Now you can use the defined operations to bring the matrix into row reduced form.
#### To do this manually, it it convenient to have 1 or -1 value in the first element 
#### of the first row(the arihtmetics of operations is easier then).
#### Performing calculations in python, won't provide much of a benefit,
#### but it is better to do that for illustration purposes, So, Let's swap the first and third rows: 


In [27]:
# note : ref is and abbreviation of the row echelon form (row reduced form ) 
A_ref = swaprows(aug_mat,0,2)
A_ref

array([[ -1,   2,  -5,  17],
       [  2,   1,   3,   0],
       [  4,  -3,   1, -10]])

In [28]:
## To turn the first element of the first and second row to zero we need to multiply it by 2 and add to second row 
A_ref = addrow(A_ref,0,2,1)
A_ref

array([[ -1,   2,  -5,  17],
       [  0,   5,  -7,  34],
       [  4,  -3,   1, -10]])

In [29]:
A_ref = addrow(A_ref,0,4,2)
A_ref

array([[ -1,   2,  -5,  17],
       [  0,   5,  -7,  34],
       [  0,   5, -19,  58]])

In [30]:
# The next step will be to turn the second element of the third row to zero
A_ref = addrow(A_ref,1,-1,2)
A_ref

array([[ -1,   2,  -5,  17],
       [  0,   5,  -7,  34],
       [  0,   0, -12,  24]])

In [31]:
# Now its easy to find out the value of x3 from the third row as it is: -12x_3 = 24
# Divide third row by -12 
A_ref = multiplyrow(A_ref,2,-1/12)
A_ref

array([[-1,  2, -5, 17],
       [ 0,  5, -7, 34],
       [ 0,  0,  1, -2]])

In [32]:
## now x3 = -2 , so x2 and x1 will be 
x_3 = -2
x_2 = (A_ref[1,3] - A_ref[1,2] * x_3) / A_ref[1,1]
x_1 = (A_ref[0,3] - A_ref[0,2] * x_3 - A_ref[0,1] * x_2) / A_ref[0,0]
print(f"Value of X1,X2,X3 = {x_1},{x_2},{x_3}")

Value of X1,X2,X3 = 1.0,4.0,-2


In [33]:
## Let's Check answer 
np.linalg.solve(A,B)

array([[ 1.],
       [ 4.],
       [-2.]])

$$
\begin{cases}
x_1 + x_2 + x_3 = 2, \\ 
x_2 - 3x_3 = 1, \\
2x_1 + x_2 + 5x_3 = 0
\end{cases}
$$

## System of Linear Equations with no Solution

In [34]:
# Determinant 
A_2 = np.array([[1,1,1],[0,1,-3],[2,1,5]])
b_2 = np.array([2,1,0])
b_2 = b_2.reshape(3,1)
A_2_system  = np.hstack((A_2,b_2))
det_a = np.linalg.det(A_2)
print(f"Determinant of matrix A_2: {det_a:.2f}")

Determinant of matrix A_2: 0.00


In [35]:
# Determinant is zero , thats why the system will have either infinite or zero solution. 
# Let's see it 
A_2_system

array([[ 1,  1,  1,  2],
       [ 0,  1, -3,  1],
       [ 2,  1,  5,  0]])

In [36]:
## Multiply row 0 by -2 to convert the third row into 0
A_2_system = addrow(A_2_system,0,-2,2)
A_2_system

array([[ 1,  1,  1,  2],
       [ 0,  1, -3,  1],
       [ 0, -1,  3, -4]])

In [37]:
## Add row_one to the row_two 
A_2_system = addrow(A_2_system,1,1,2)
A_2_system

array([[ 1,  1,  1,  2],
       [ 0,  1, -3,  1],
       [ 0,  0,  0, -3]])

#### So The last row will correspond to the equation which has no solution.
#### Thus the whole linear system has no solution.

##  System of Linear Equations with infinite numbers of solution 
$$
\begin{cases}
x_1 + x_2 + x_3 = 2, \\ 
x_2 - 3x_3 = 1, \\
2x_1 + x_2 + 5x_3 = 3
\end{cases}
$$


In [40]:
## We can bring this system to consistency by seperating co - efficiant and the value 
A_3 = np.array([[1,1,1],[0,1,-3],[2,1,5]])
b_3 = np.array([2,1,3])
b_3 = b_3.reshape(3,1)
A_3_system = np.hstack((A_3,b_3))

In [41]:
pd.DataFrame(A_3_system)

,0,1,2,3
0,1,1,1,2
1,0,1,-3,1
2,2,1,5,3


In [42]:
## We need to make the first element of third row 0
A_3_system = addrow(A_3_system,0,-2,2)
A_3_system

array([[ 1,  1,  1,  2],
       [ 0,  1, -3,  1],
       [ 0, -1,  3, -1]])

In [43]:
## Second element of the third row is now zero 
A_3_system = addrow(A_3_system,1,1,2)
A_3_system

array([[ 1,  1,  1,  2],
       [ 0,  1, -3,  1],
       [ 0,  0,  0,  0]])

## Thus from the corresponding linear system , we've got 
$$
\begin{cases}
x_1 + x_2 + x_3 = 2, \\ 
x_2 - 3x_3 = 1, \\
0 = 0
\end{cases}
$$

#### From the second and third row we'll find 
$$
\begin{cases}
x_1 = 1 - 4x_3, \\
x_2 = 1 + 3x_3
\end{cases}
$$

#### Where **x3** could be any real number