# Read, Explain and Hide 

In [22]:
## Class One Week One

In [23]:
# Importing Materials 
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt 
import datetime
print(f"Last Updated:{datetime.datetime.now()}")

Last Updated:2026-02-01 09:44:28.934715


In [24]:
# Introduction to python matrices and numpy 

In [25]:
# Run the "Hello World" in the cell below to print "Hello World". 
test = "Hello World"

In [26]:
print(test)

Hello World


In [27]:
# Checking the array object 
one_dim_arr= np.array([10,3,6,9,5,7])
one_dim_arr

array([10,  3,  6,  9,  5,  7])

In [28]:
one_dim_arr.ndim

1

In [29]:
# Using arange Create an array with 3 integers, starting from the default integer 0.
a = np.arange(4)
a   ## Shift + Tab opens the documentation.

array([0, 1, 2, 3])

In [30]:
# Create an array that starts from the integer 1, ends at 20, incremented by 3
b = np.arange(1,20,3) # Start,Stop,Step
b

array([ 1,  4,  7, 10, 13, 16, 19])

In [31]:
# Using linspace (Linearly Spaced)
lin_spaced_arr = np.linspace(0,100,5) # It says: give 5 equally spaced numbers within 0 - 100
lin_spaced_arr

array([  0.,  25.,  50.,  75., 100.])

In [32]:
c = np.arange(0,100,25)
c  # Problem with arange()

array([ 0, 25, 50, 75])

In [33]:
# Notice results shown in the float datatype (default) to change use dtype()
lin_spaced_arr = np.linspace(0,100,5,dtype=int)
lin_spaced_arr # int

array([  0,  25,  50,  75, 100])

In [34]:
char_arr = np.array(["Welcome to Math for ML!"])
print(char_arr)

['Welcome to Math for ML!']


In [35]:
print(f"Content:{char_arr}")
print(f"Data Type:{char_arr.dtype}")
print(f"Shape:{char_arr.shape}")

Content:['Welcome to Math for ML!']
Data Type:<U23
Shape:(1,)


### '<' stands for little endian , 'U' stands for Unicode and 23 stands for 'number of character in the string'
### In Numpy array string is not just text it's a sequence of character.

In [36]:
# Using np.ones()    It returns an array of just one (float default)
ones_arr = np.ones(10,dtype=int) 
ones_arr 

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [37]:
# Using np.zeros()    It returns an array of just zero (float default)
zero_arr = np.zeros(10,dtype=int) 
zero_arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [38]:
# Using np.empty()
empt_arr = np.empty(17)
empt_arr

# This function doesn't clean the leftover memory what it does is it just overwrite over garbage
# Super effective to clean up memory and increasing performance but not very handy to use

array([4.67296746e-307, 1.69121096e-306, 8.34451079e-308, 2.04721870e-306,
       6.23054972e-307, 2.22522597e-306, 1.33511969e-306, 1.37962320e-306,
       9.34604358e-307, 9.79101082e-307, 1.78020576e-306, 1.69119873e-306,
       2.22522868e-306, 1.24611809e-306, 8.06632139e-308, 1.60221208e-306,
       2.29178686e-312])

In [39]:
rand_arr = np.random.rand(3)
rand_arr # Some random default float numbers.

array([0.48705996, 0.2702934 , 0.85598589])

## Multidimentional Array

In [40]:
# 2 - Dimentional Array 
two_dim_arr = np.array([[10,20,30],
                      [30,20,10]])
two_dim_arr

array([[10, 20, 30],
       [30, 20, 10]])

In [43]:
# An alternative way to create a multidimensional array is by reshaping the initial 1-D array.
# Using np.reshape() you can rearrange elements of the previous array into a new shape.
multi_dim_arr = one_dim_arr.reshape(2,3) # or np.reshape(one_dim_arr,(2,3))
multi_dim_arr # reshaping will work only if (array to reshape) = (given shape) *number wise

array([[10,  3,  6],
       [ 9,  5,  7]])

In [44]:
                                  ## Finding size,shape and dimention. 
np.size(muliti_dim_arr) , one_dim_arr.shape , muliti_dim_arr.ndim

(6, (6,), 2)

In [45]:
                                        ## Array math operations 
arr_1 = np.arange(1,10,2)
arr_2 = np.arange(1,20,4)
# Basic operation between two 1-d arrays 
addition = arr_1 + arr_2 ,
subtraction = arr_1 - arr_2 ,
multiplication = arr_1 * arr_2 ,
division = arr_2 / arr_1

In [46]:
addition,subtraction,multiplication,division

((array([ 2,  8, 14, 20, 26]),),
 (array([ 0, -2, -4, -6, -8]),),
 (array([  1,  15,  45,  91, 153]),),
 array([1.        , 1.66666667, 1.8       , 1.85714286, 1.88888889]))

In [47]:
                       ## Broadcasting is just multiplying a vector with a scalar
## We are suppose to convert miles into kilometre
vector = np.array([[1,2,3,4],[5,6,7,8]])
scalar = 1.6
broadcasting = vector * scalar
broadcasting

array([[ 1.6,  3.2,  4.8,  6.4],
       [ 8. ,  9.6, 11.2, 12.8]])

## Indexing and Slicing 

In [48]:
"""Indexing is very useful as it allows to select specefic elements from an array. It also let us select
 entire rows/columns or planes as you'll see in future assignments for multidimentional arrays"""

"Indexing is very useful as it allows to select specefic elements from an array. It also let us select\n entire rows/columns or planes as you'll see in future assignments for multidimentional arrays"

In [49]:
## Indexing 
a = np.random.randint(2,10,size= 4)
# Select the third element of the array. Remember the counting starts from 0
a,a[2]

(array([6, 5, 7, 7], dtype=int32), np.int32(7))

In [50]:
# For multidimentional arrays of shape n to index a specefic element,
# you must put n indices, one for each dimention
two_dim_arr , two_dim_arr.ndim

(array([[10, 20, 30],
        [30, 20, 10]]),
 2)

In [51]:
# Indexing on 2-D array 
two_dim_arr[0,1]

np.int64(20)

In [52]:
# Select Element number 4 from array 
two_dim_arr[1,0]

np.int64(30)

In [53]:
# Access 20 and 30 or the last row 
two_dim_arr[1,0:2]

array([30, 20])

### Difference between indexing and slicing is slicing works better on multidimentional array 
### Slicing is end exclusive. syntax: [Start:End:Stop]
### Default Start = 0  and end = length of array - 1 also by default the step is 1

In [65]:
# Slice the two_dim array to get the first two rows
ran_tda = np.random.randint(0,20,size=(4,4))
ran_tda[2:]

array([[16,  0,  4, 15],
       [ 1, 19, 18, 12]], dtype=int32)

In [70]:
ran_tda

array([[13, 16,  2,  0],
       [11,  4, 12,  6],
       [16,  0,  4, 15],
       [ 1, 19, 18, 12]], dtype=int32)

In [71]:
ran_tda[:] ## ran_tda == ran_tda[:]

array([[13, 16,  2,  0],
       [11,  4, 12,  6],
       [16,  0,  4, 15],
       [ 1, 19, 18, 12]], dtype=int32)

In [73]:
ran_tda[::] # ran_tda == ran_tda[:] == ran_tda[::]

array([[13, 16,  2,  0],
       [11,  4, 12,  6],
       [16,  0,  4, 15],
       [ 1, 19, 18, 12]], dtype=int32)

In [75]:
ran_tda[:,1]

array([16,  4,  0, 19], dtype=int32)

In [76]:
# Stacking 
# Stacking is the feature of Numpy that leads to increased customizaiton of arrays.
# It means to join two or more arrays, either horizontally or vertically. Meaning that it's done along a new axis

In [77]:
# np.vstack() - stack vertically 
# np.hstack() - stack horizontally 
# np.hsplit() - splits an array into several smaller arrays. 

In [80]:
a1 = np.random.randint(8,12,size=(2,4))
a2 = np.random.randint(10,14,size=(2,4))
a1,a2

(array([[10,  9, 10,  9],
        [ 9, 11, 10,  9]], dtype=int32),
 array([[12, 13, 12, 11],
        [13, 10, 11, 10]], dtype=int32))

In [87]:
vert_arr = np.vstack((a1,a2))
vert_arr   ## It glues two arrays vertically

array([[10,  9, 10,  9],
       [ 9, 11, 10,  9],
       [12, 13, 12, 11],
       [13, 10, 11, 10]], dtype=int32)

In [89]:
hor_arr = np.hstack((a1,a2))
hor_arr   ## It glues arrays horizontally

array([[10,  9, 10,  9, 12, 13, 12, 11],
       [ 9, 11, 10,  9, 13, 10, 11, 10]], dtype=int32)

In [91]:
# Is there a difference between np.zeros() and np.empty()? Select one of the options given:

    # A. No difference, they both output arrays of zeros.
    # B. np.zeros() is not initialized, but gives an output of zeros.
    # C. np.zeros() is faster to execute than np.empty().
    # D. np.empty() outputs an uninitialized array, but np.zeros() outputs an initialized array of value zero.

### The answer is "D"