In [1]:
import numpy as np
import torch
import matplotlib as plt

In [7]:
n1 = 4
n2 = 12
n3 = 20

## L2 norm is just a fancy way of saying the distance. Reffered as : ||x||2   or ||x||

In [8]:
## Lets say (x1, x2) = (4,12)
## So L2 norm is : 
L2_norm = (4**2 + 12**2)*(1/2)
L2_norm

80.0

## L1 norm is just simply adding the values of a vector { Absolute Values }. Refferd as: ||x||1

In [9]:
x1 = -4
x2 = -12
x3 = 20

# Let's say V = [x1 = -4, x2 = -12, x3 = 20] 

In [12]:
L1_norm = np.abs(x1) + np.abs(x2) + np.abs(x3)
L1_norm

np.int64(36)

In [ ]:
## Squared L2 norm is just adding those values but squared. Denoted as : ||x||2
##                                                                            2

In [29]:
squared_l2_norm = (n1**2) + (n2**2) + (n3**2)
squared_l2_norm

560

## Also squared L2 norm = X^T.X

In [21]:
x = np.array([[4,12,20]])
x

array([[ 4, 12, 20]])

In [22]:
x_transposed = x.T
x_transposed

array([[ 4],
       [12],
       [20]])

In [26]:
s_l2_norm = x_transposed*x
s_l2_norm

array([[ 16,  48,  80],
       [ 48, 144, 240],
       [ 80, 240, 400]])

## Max Norm
### Max norm means the maximum absolute value of a vector

In [3]:
Mx_nm = [-25,-20,5]

max_norm = np.max([np.abs(-25),np.abs(-20),np.abs(5)])
max_norm

np.int64(25)

## Genaralized Lp Norm

### Generalized Lp norm is just putting the required value right beside a norm vector... P must be a real number and greater or equal to 1