## Scalar, Vector, Matrices and Tensor
### Scalar - 2,5,-8,9,0.5 (A single numerical value) - 0 dimentional
### Vector - [2, 4, -1] (An ordered list of numbers (magnitude and direction)) - 1 dimentional
### Matrices - [[1, 2],[3, 4]] (A 2D array of numbers arranged in rows and columns) - 2 dimentional
### Tensors - [[[1,2],[3,4]],[[5,6],[7,8]]] (A generalization of scalars, vectors, and matrices to higher dimensions) - 3,4,5,6....n dimentional

In [41]:
# Scalar is also called as "rank-0" tensor
import torch
import tensorflow as tf

In [42]:
x = 25
x

25

In [43]:
type(x)

int

In [44]:
y = 25
py_sum = x+y
py_sum

50

In [45]:
type(py_sum)

int

In [46]:
x_float = 25.0
float_sum = x_float + y
float_sum

50.0

In [47]:
type(float_sum)

float

In [48]:
x_pt = torch.tensor(33)
x_pt

tensor(33)

In [49]:
x_pt.shape   #Blank list refers to the sclar data type

torch.Size([])

## Scalars in TensorFlow
## Tensors created with a wrapper

### tf.Variable
### tf.constant
### tf.placeholder
### tf.SparseTensor


In [57]:
x_tf = tf.Variable(95,dtype = tf.int32)
x_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=95>

In [58]:
y_tf = tf.Variable(5,size=(tf.int32))
y_tf

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=5>

In [59]:
x_tf.shape

TensorShape([])

In [60]:
sum_tf = tf.add(x_tf,y_tf)
sum_tf

<tf.Tensor: shape=(), dtype=int32, numpy=100>

In [61]:
sub_tf = tf.subtract(sum_tf,y_tf)
sub_tf

<tf.Tensor: shape=(), dtype=int32, numpy=95>

In [65]:
sum_tf.numpy()   # note that NumPy operations automatically convert tensors to NumPy arrays, and vice versa

np.int32(100)

In [69]:
type(sum_tf)

tensorflow.python.framework.ops.EagerTensor

In [70]:
sum_tf.dtype

tf.int32

In [50]:
#num_1 = tf.Variable(25,dtype=tf.int64)
#num_2 = tf.Variable(4.50,dtype=tf.float64)
#sum_2 = tf.add(num_1,num_2)
#sum_2  # cannot add two number with two different datatype

In [71]:
num_1 = tf.Variable(25,dtype=tf.float64)
num_2 = tf.Variable(4.50,dtype=tf.float64)
sum_2 = tf.add(num_1,num_2)
sum_2

<tf.Tensor: shape=(), dtype=float64, numpy=29.5>