## Use SHIFT+TAB to see the docstring of the function --
## Creating Numpy Arrays ---

In [2]:
### Different Ways To Create An Arrray
import numpy as np
array_1 = np.array([1,2,3,4,5,6,7,8,9])
array_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
# Array Using One
array_2 = np.ones(20)
array_2

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1.])

In [4]:
array_3 = np.ones([2,3,3])
array_3

array([[[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]])

In [5]:
array_3.dtype

dtype('float64')

In [65]:
type(array_3)

numpy.ndarray

In [7]:
array_4 = np.zeros([3,2,3])
array_4

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [5]:
array_5 = np.arange(2,20,2)#(Start, Stop and Step)
array_5

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [9]:
random_array_1 = np.random.randint(10,20, size =(3,2,4))
random_array_1

array([[[12, 11, 10, 16],
        [16, 16, 18, 10]],

       [[16, 19, 19, 12],
        [10, 19, 14, 10]],

       [[13, 18, 13, 11],
        [17, 14, 18, 17]]], dtype=int32)

In [10]:
type(random_array_1),random_array_1.dtype,random_array_1.size,random_array_1.shape

(numpy.ndarray, dtype('int32'), 24, (3, 2, 4))

In [11]:
array_7 = np.arange(0,100,2)
array_7

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [12]:
array_8 = np.random.randint(10,30, size=(3,3,3)) # This will return a list of random numbers in integer
array_8

array([[[26, 12, 17],
        [17, 22, 29],
        [15, 10, 23]],

       [[27, 25, 16],
        [10, 16, 22],
        [19, 15, 22]],

       [[14, 29, 22],
        [23, 27, 21],
        [20, 15, 25]]], dtype=int32)

In [17]:
random_array_2 = np.random.random((3,2,4)) # It creates random float numbers but not specified

In [19]:
random_array_2.size,random_array_2.shape,random_array_2.dtype,type(random_array_2)

(24, (3, 2, 4), dtype('float64'), numpy.ndarray)

In [16]:
# Psuedo-random numbers 
# np.random.seed()

In [25]:
np.random.seed(0)  ## If there is any real numbers without 0 it changes for once.
random_array_3 = np.random.randint(10,25, size=(3,2,4))
random_array_3

array([[[22, 15, 10, 13],
        [21, 13, 17, 19]],

       [[13, 15, 12, 14],
        [17, 16, 18, 18]],

       [[22, 20, 11, 16],
        [17, 17, 24, 18]]], dtype=int32)

In [64]:
random_array_3 = np.random.randint(10,25, size=(3,2,4))   ## This Changes every time
random_array_3

array([[[15, 24, 10, 11],
        [12, 14, 12, 10]],

       [[23, 13, 12, 20],
        [23, 10, 17, 15]],

       [[19, 10, 20, 12],
        [21, 20, 17, 21]]], dtype=int32)