## Viewing Arrays And Matrices

In [17]:
import numpy as np 

In [18]:
np.random.seed(0)
a1 = np.random.randint(0,25,size=(3,2,4))
a1

array([[[12, 15, 21,  0],
        [ 3,  3,  7,  9]],

       [[19, 21, 18,  4],
        [23,  6, 24, 24]],

       [[12,  1,  6,  7],
        [23, 14, 24, 17]]], dtype=int32)

In [19]:
np.unique(a1)

array([ 0,  1,  3,  4,  6,  7,  9, 12, 14, 15, 17, 18, 19, 21, 23, 24],
      dtype=int32)

In [20]:
a1.shape

(3, 2, 4)

In [21]:
a1[0]

array([[12, 15, 21,  0],
       [ 3,  3,  7,  9]], dtype=int32)

In [22]:
a1[1]

array([[19, 21, 18,  4],
       [23,  6, 24, 24]], dtype=int32)

In [23]:
a1[2]

array([[12,  1,  6,  7],
       [23, 14, 24, 17]], dtype=int32)

In [24]:
a1[0,1]

array([3, 3, 7, 9], dtype=int32)

In [25]:
a2 = np.random.randint(0,20, size=(3,3,3))
a2

array([[[ 5, 13,  8],
        [ 9, 19, 16],
        [19,  5, 15]],

       [[15,  0, 18],
        [ 3, 17, 19],
        [19, 19, 14]],

       [[ 7,  0,  1],
        [ 9,  0, 10],
        [ 3, 11, 18]]], dtype=int32)

In [26]:
a2[0:2,0:2,0:2]

array([[[ 5, 13],
        [ 9, 19]],

       [[15,  0],
        [ 3, 17]]], dtype=int32)

In [34]:
np.random.seed(0)
a3 = np.random.randint(0,10,size=(2,3,4,5))
a3

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]], dtype=int32)

In [35]:
a3.shape,a3.size

((2, 3, 4, 5), 120)

In [36]:
# Get the first 4 numbers of the inner most arrays

In [37]:
a3[:,:,:,3]

array([[[3, 2, 8, 8],
        [9, 5, 1, 0],
        [4, 2, 5, 4]],

       [[7, 7, 9, 4],
        [4, 0, 0, 4],
        [0, 2, 3, 1]]], dtype=int32)

In [38]:
a3[1,2,2,:]

array([2, 9, 2, 3, 3], dtype=int32)

In [32]:
a3

array([[[[5, 0, 3, 3, 7],
         [9, 3, 5, 2, 4],
         [7, 6, 8, 8, 1],
         [6, 7, 7, 8, 1]],

        [[5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3],
         [3, 3, 7, 0, 1]],

        [[9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6],
         [8, 4, 1, 4, 9]]],


       [[[8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4],
         [4, 6, 4, 4, 3]],

        [[4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5],
         [0, 1, 2, 4, 2]],

        [[0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3],
         [2, 3, 4, 1, 2]]]], dtype=int32)

In [33]:
a3[0,2,:,:]

array([[9, 9, 0, 4, 7],
       [3, 2, 7, 2, 0],
       [0, 4, 5, 5, 6],
       [8, 4, 1, 4, 9]], dtype=int32)

In [55]:
a3[1,:,:,:]

array([[[8, 1, 1, 7, 9],
        [9, 3, 6, 7, 2],
        [0, 3, 5, 9, 4],
        [4, 6, 4, 4, 3]],

       [[4, 4, 8, 4, 3],
        [7, 5, 5, 0, 1],
        [5, 9, 3, 0, 5],
        [0, 1, 2, 4, 2]],

       [[0, 3, 2, 0, 7],
        [5, 9, 0, 2, 7],
        [2, 9, 2, 3, 3],
        [2, 3, 4, 1, 2]]], dtype=int32)

## It works by outer most to inner most.
## [:] denotes all of the from the selected
## and its very easyy