# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import pandas as pd 
import numpy as np 
%matplotlib inline
import matplotlib.pyplot as plt 
from matplotlib.image import imread
import datetime
print(f"Last Updated:{datetime.datetime.now()}")

Last Updated:2026-01-03 19:37:01.292457


In [2]:
# Create a 1-dimensional NumPy array using np.array()
array_1 = np.array([1,2,3,4,5,6])
array_1
# Create a 2-dimensional NumPy array using np.array()
array_2 = np.array([[1,2,3],[4,5,6]])
array_2
# Create a 3-dimensional Numpy array using np.array()
array_3 = np.array([[[1,2,3],
                  [4,5,6]],
                  [[7,8,9],
                  [10,11,12]]])
array_3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
array_1.ndim,array_1.size,array_1.shape,type(array_1),array_1.dtype,array_1.itemsize,array_1.nbytes

(1, 6, (6,), numpy.ndarray, dtype('int64'), 8, 48)

In [4]:
# Attributes of 2-dimensional array
array_2.dtype,type(array_2),array_2.size,array_2.itemsize,array_2.shape,array_2.nbytes,array_2.ndim

(dtype('int64'), numpy.ndarray, 6, 8, (2, 3), 48, 2)

In [5]:
# Attributes of 3-dimensional array
array_3.ndim,array_3.size,array_3.shape,type(array_3),array_3.dtype,array_3.itemsize,array_3.nbytes

(3, 12, (2, 2, 3), numpy.ndarray, dtype('int64'), 8, 96)

In [6]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
df_1 = pd.DataFrame(array_2)
df_1

0  1  2
0  1  2  3
1  4  5  6

In [7]:
# Create an array of shape (10, 2) with only ones
one_array = np.ones((10,2)).astype(int)
one_array

array([[1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1],
       [1, 1]])

In [8]:
# Create an array of shape (7, 2, 3) of only zeros
zero_array = np.zeros((7,2,3))
zero_array.astype(int)

array([[[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0]]])

In [9]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [10]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
np.random.seed(0)
random_array1 = np.random.randint(0,10,size=(7,2))
random_array1

array([[5, 0],
       [3, 3],
       [7, 9],
       [3, 5],
       [2, 4],
       [7, 6],
       [8, 8]], dtype=int32)

In [11]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
np.random.seed(0)
random_array2 = np.random.random((7,2))
random_array2

array([[0.5488135 , 0.71518937],
       [0.60276338, 0.54488318],
       [0.4236548 , 0.64589411],
       [0.43758721, 0.891773  ],
       [0.96366276, 0.38344152],
       [0.79172504, 0.52889492],
       [0.56804456, 0.92559664]])

In [12]:
# Set the random seed to 42
# Create a random array of numbers between 0 & 10 of size (4, 6)
rng = np.random.default_rng(seed=42)
random_array3 = rng.integers(low=0,high=10,size=(4,6))
random_array3

array([[0, 7, 6, 4, 4, 8],
       [0, 6, 2, 0, 5, 9],
       [7, 7, 7, 7, 5, 1],
       [8, 4, 5, 3, 1, 9]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [13]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4 = rng.integers(low=1,high=10,size=(3,7))
random_array4
# Find the unique numbers in the array you just created
np.unique(random_array4)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [14]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([8, 6, 4, 8, 5, 4, 5])

In [15]:
random_array4

array([[8, 6, 4, 8, 5, 4, 5],
       [3, 1, 5, 8, 1, 8, 8],
       [3, 6, 2, 7, 7, 4, 1]])

In [16]:
# Get the first 2 rows of latest array you created
random_array4[0:2,:7]

array([[8, 6, 4, 8, 5, 4, 5],
       [3, 1, 5, 8, 1, 8, 8]])

In [17]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[0:2,0:2]

array([[8, 6],
       [3, 1]])

In [18]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
random_array5 = rng.integers(low=0,high=10,size=(3,5))
random_array6 = np.ones((3,5)).astype(int)

In [19]:
# Add the two arrays together
sum1 = sum(random_array5,random_array6)
sum1

array([[17, 11, 13, 18, 18],
       [17, 11, 13, 18, 18],
       [17, 11, 13, 18, 18]])

In [20]:
# Create another array of ones of shape (5, 3)
random_array7 = np.ones((5,3)).astype(int)
random_array7

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [21]:
# Try add the array of ones and the other most recent array together
sum2 = sum(sum1,random_array7.T)
sum2

array([[52, 34, 40, 55, 55],
       [52, 34, 40, 55, 55],
       [52, 34, 40, 55, 55]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [22]:
# Create another array of ones of shape (3, 5)
random_array8 = np.ones((3,5)).astype(int)
random_array8

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [23]:
# Subtract the new array of ones from the other most recent array
sub1 = sum2 - random_array8
print(sub1)

[[51 33 39 54 54]
 [51 33 39 54 54]
 [51 33 39 54 54]]


In [24]:
# Multiply the ones array with the latest array
mul1 = random_array8 * sub1
mul1

array([[51, 33, 39, 54, 54],
       [51, 33, 39, 54, 54],
       [51, 33, 39, 54, 54]])

In [25]:
# Take the latest array to the power of 2 using '**'
mul1 ** 2

array([[2601, 1089, 1521, 2916, 2916],
       [2601, 1089, 1521, 2916, 2916],
       [2601, 1089, 1521, 2916, 2916]])

In [26]:
# Do the same thing with np.square()
np.square(mul1)

array([[2601, 1089, 1521, 2916, 2916],
       [2601, 1089, 1521, 2916, 2916],
       [2601, 1089, 1521, 2916, 2916]])

In [27]:
# Find the mean of the latest array using np.mean()
np.mean(mul1)

np.float64(46.2)

In [28]:
# Find the maximum of the latest array using np.max()
np.max(mul1)

np.int64(54)

In [29]:
# Find the minimum of the latest array using np.min()
np.min(mul1)

np.int64(33)

In [30]:
# Find the standard deviation of the latest array
np.std(mul1)

np.float64(8.611620056644394)

In [31]:
# Find the variance of the latest array
np.var(mul1)

np.float64(74.16)

In [32]:
# Reshape the latest array to (3, 5, 1)
mul1.reshape(3,5,1)

array([[[51],
        [33],
        [39],
        [54],
        [54]],

       [[51],
        [33],
        [39],
        [54],
        [54]],

       [[51],
        [33],
        [39],
        [54],
        [54]]])

In [33]:
# Transpose the latest array
mul1.T

array([[51, 51, 51],
       [33, 33, 33],
       [39, 39, 39],
       [54, 54, 54],
       [54, 54, 54]])

What does the transpose do?

In [34]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
random_array9 = rng.integers(low=0,high=10,size=(3,3))
random_array10 = rng.integers(low=0,high=10,size=(3,2))

In [35]:
# Perform a dot product on the two newest arrays you created
random_array9 @ random_array10

array([[ 46, 109],
       [ 43,  97],
       [ 39,  75]])

In [36]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_array11 = rng.integers(low=0,high=10,size=(4,3))
random_array12 = rng.integers(low=0,high=10,size=(4,3))

In [37]:
# Perform a dot product on the two newest arrays you created
np.dot(random_array11,random_array12)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [38]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(random_array11,random_array12.T)

array([[ 49,  56,  40,  38],
       [129, 140,  81, 100],
       [ 83,  88,  36,  62],
       [ 67,  80,  74,  54]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [39]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
ran_arr_13 = rng.integers(low=0,high=10,size=(4,4))
ran_arr_14 = rng.integers(low=0,high=10,size=(4,4))

In [40]:
# Compare the two arrays with '>'
ran_arr_13 > ran_arr_14

array([[False,  True, False,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [False, False, False, False]])

What happens when you compare the arrays with `>`?

In [41]:
# Compare the two arrays with '>='
ran_arr_13 >= ran_arr_14

array([[False,  True,  True,  True],
       [False,  True,  True,  True],
       [ True, False,  True,  True],
       [ True,  True, False,  True]])

In [42]:
# Find which elements of the first array are greater than 7
filtered_elements = ran_arr_13[ran_arr_13 > 7] 
filtered_elements

array([8, 8])

In [43]:
ran_arr_13

array([[1, 8, 1, 8],
       [0, 7, 7, 7],
       [6, 4, 7, 2],
       [7, 5, 4, 5]])

In [44]:
ran_arr_14

array([[5, 0, 1, 2],
       [1, 4, 6, 6],
       [4, 8, 5, 0],
       [7, 5, 6, 5]])

In [45]:
# Which parts of each array are equal? (try using '==')
equal_elements = ran_arr_13[ran_arr_13 == ran_arr_14]
equal_elements

array([1, 7, 5, 5])

In [46]:
# Sort one of the arrays you just created in ascending order
np.sort(ran_arr_13)

array([[1, 1, 8, 8],
       [0, 7, 7, 7],
       [2, 4, 6, 7],
       [4, 5, 5, 7]])

In [50]:
# Sort the indexes of one of the arrays you just created
np.argsort(ran_arr_13)

array([[0, 2, 1, 3],
       [0, 1, 2, 3],
       [3, 1, 0, 2],
       [2, 1, 3, 0]])

In [51]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(ran_arr_13)

np.int64(1)

In [52]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(ran_arr_13)

np.int64(4)

In [54]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(ran_arr_13,axis=1)

array([1, 1, 2, 0])

In [55]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmin(ran_arr_13,axis=0)

array([1, 2, 0, 2])

In [59]:
# Create an array of normally distributed random numbers
# Here loc = mean, scale = standard deviation, size = shape
nor_dis_ran_num = np.random.normal(loc=0,scale=1,size=(3,3))
print(nor_dis_ran_num)

[[-1.42001794 -1.70627019  1.9507754 ]
 [-0.50965218 -0.4380743  -1.25279536]
 [ 0.77749036 -1.61389785 -0.21274028]]


In [67]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(1,10,20,endpoint=False)

array([1.  , 1.45, 1.9 , 2.35, 2.8 , 3.25, 3.7 , 4.15, 4.6 , 5.05, 5.5 ,
       5.95, 6.4 , 6.85, 7.3 , 7.75, 8.2 , 8.65, 9.1 , 9.55])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.