## Vectors (Rank 1 Tensors) in NumPy

### Vectors and Vector Transposition
### In General Vector Transposition means Column and Rows Transposed Their Gender
### Column -> Rows, Rows -> Column

In [2]:
# Vector Transposition ------
import numpy as np
x = np.array([1,2,3,4,5,6])
x

array([1, 2, 3, 4, 5, 6])

In [3]:
# Transposing a regular 1-D array has no effect...
x_trans = x.T
x_trans

array([1, 2, 3, 4, 5, 6])

In [4]:
x_trans.shape

(6,)

In [5]:
x_trans.ndim

1

In [10]:
# ...but it does we use nested "matrix-style" brackets:
x_ms = np.array([[1,2,3,4]])
x_ms.T

array([[1],
       [2],
       [3],
       [4]])

In [11]:
x_ms.shape

(1, 4)

In [12]:
type(x_ms)

numpy.ndarray

In [13]:
# Zero Indexed

In [15]:
zero = np.array([])

In [20]:
zero.dtype

dtype('float64')

In [24]:
array_1 = np.array([1,2,3,4])

In [25]:
array_1.T

array([1, 2, 3, 4])

In [35]:
# ...but can transpose a matrix with a dimension of length 1
array_2 = np.array([0])

In [52]:
matrix = np.random.randint(0,10,size=(1,4))
matrix

array([[8, 0, 3, 1]], dtype=int32)

In [53]:
t_m = matrix.T

In [54]:
# It's 2-dimentional and it's called as matrix as well as column vector(must be 1 columned)
matrix.shape

(1, 4)

In [55]:
t_m

array([[8],
       [0],
       [3],
       [1]], dtype=int32)

## Zero Vectors

In [64]:
zero_vector = np.zeros(20)
zero_vector

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0.])

In [65]:
matrix

array([[8, 0, 3, 1]], dtype=int32)

In [62]:
np.sum(matrix,zero_vector) # Scalar and vector can't be added

TypeError: only integer scalar arrays can be converted to a scalar index

## Vector in pytorch and Tensorflow

In [ ]:
import torch

In [86]:
array_pt = torch.tensor([2,2,5,8])
array_pt

tensor([2, 2, 5, 8])

In [87]:
array_pt_1 = torch.tensor([[2,2,5,8]])
array_pt_1

tensor([[2, 2, 5, 8]])

In [88]:
array_pt.dtype

torch.int64

In [89]:
type(array_pt)

torch.Tensor

In [90]:
array_pt_1.T

tensor([[2],
        [2],
        [5],
        [8]])

In [85]:
import tensorflow as tf

In [100]:
x_tf_2 = tf.Variable([1,2,3,4,5,6])
x_tf_2

<tf.Variable 'Variable:0' shape=(6,) dtype=int32, numpy=array([1, 2, 3, 4, 5, 6], dtype=int32)>

In [102]:
x_tf_2.Transpose


AttributeError: 'ResourceVariable' object has no attribute 'T'