In [3]:
# Importing Materials 
import pandas as pd 
import numpy as np 
%matplotlib inline 
import matplotlib.pyplot as plt 
import datetime
print(f"Last Updated:{datetime.datetime.now()}")

Last Updated:2026-02-15 10:38:28.772054


In [4]:
print("Hello Algebra")

Hello Algebra


In [5]:
one_dim_array = np.array([10,12,14,16,18])
one_dim_array

array([10, 12, 14, 16, 18])

In [6]:
# Create an array with 3 integers, starting from the default integer 0.
np.arange(0,3,1)

array([0, 1, 2])

In [7]:
# Using Linspace --- Linspace stands for Linearly Spaced values. 
np.linspace(0,100,50,dtype = int)

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  51,
        53,  55,  57,  59,  61,  63,  65,  67,  69,  71,  73,  75,  77,
        79,  81,  83,  85,  87,  89,  91,  93,  95,  97, 100])

In [8]:
char_arr = np.array(["Welcome to Math for ML!"])
char_arr

array(['Welcome to Math for ML!'], dtype='<U23')

In [9]:
ones_array = np.ones(3)
ones_array

array([1., 1., 1.])

In [10]:
zeros_array = np.zeros(5)
zeros_array

array([0., 0., 0., 0., 0.])

In [11]:
empty_array = np.empty(5)
empty_array

array([0., 0., 0., 0., 0.])

In [12]:
rand_arr = np.random.rand(3)
rand_arr

array([0.82727549, 0.85330077, 0.27019283])

In [13]:
# 2 Dimentional Array 
two_dim_array = np.array([[4,54,6,7],[54,7,8,9]])
two_dim_array

array([[ 4, 54,  6,  7],
       [54,  7,  8,  9]])

In [14]:
# Multidimentional Array using reshape 
two_dim_array.reshape(1,4,2)
two_dim_array.ndim

2

In [15]:
two_dim_array.size

8

In [16]:
## Broadcasting Method 
# by broadcasting we can perform operations specifically on arrays of different shapes 
vector = np.array([1,2])
vector * 1.6

array([1.6, 3.2])

In [17]:
# indexing on 2-d array 
tda = np.random.randint(0,10,size=[1,5,3])
tda.ndim

3

In [18]:
tda

array([[[0, 3, 6],
        [8, 7, 6],
        [4, 5, 6],
        [4, 4, 0],
        [1, 4, 2]]], dtype=int32)

In [19]:
tda[0,2,1]

np.int32(5)

In [20]:
# Slice the array to get [1, 2, 1]     [Start:Stop:Step]
tda[0,1,1:2]

array([7], dtype=int32)

In [21]:
tda[0,:,2]

array([6, 6, 6, 0, 2], dtype=int32)

In [22]:
tda[::2]

array([[[0, 3, 6],
        [8, 7, 6],
        [4, 5, 6],
        [4, 4, 0],
        [1, 4, 2]]], dtype=int32)

In [23]:
np.vstack((tda))

array([[0, 3, 6],
       [8, 7, 6],
       [4, 5, 6],
       [4, 4, 0],
       [1, 4, 2]], dtype=int32)

In [24]:
np.hstack((tda))

array([[0, 3, 6],
       [8, 7, 6],
       [4, 5, 6],
       [4, 4, 0],
       [1, 4, 2]], dtype=int32)

## Solving Linear Systime 2 Variable 

A **system of linear equations** or **linear system** is a collection of one or more linear equations involving the same variable. For example: 
$$
\begin{cases}
-x_1 + 3x_2 = 7 ,\\
3x_1 + 2x_2 = 1
\end{cases}
$$
This is a system of two equations with two unknown variable **x_1,x_2**.To Solve a system of linear equations means to find such values of the variables **x_1,x_2** , that all of its equations are simultaneously satisfied.

A linear system is **inconsistent** if its has no solution and otherwise it is said to be **consistent**.
Consistent system can have one or infinite number of solutions.

In [25]:
# In order to perform the calc we need to input seperately both co - efficiant and values (array).
# A stands for co-efficiant and b stands for value and x stands for answer 
A = np.array([[-1,3],
     [3,2]])
b = np.array([7,1])
x = np.linalg.solve(A,b) 
x

array([-1.,  2.])

In [26]:
x.shape,A.shape,b.shape

((2,), (2, 2), (2,))

In [27]:
## We need to checkout if the number or answer is correct 
x_1 , x_2 = x
check_1 = -1*x_1 + 3*x_2
check_2 = 3*x_1 + 2*x_2
print(f"Answer of the first equation is : {check_1}")
print(f"Answer of the second equation is : {check_2}")

Answer of the first equation is : 7.0
Answer of the second equation is : 1.0


In [33]:
## The previous step was manual step now we'll see the automatic step to check the result 
x1,x2 = x
if np.allclose(np.dot(A,x),b): 
    print("Correct")
else: 
    print("Incorrect")

Correct


In [37]:
## Checking if the equation have any answer or not by using np.linalg.det()
np.linalg.det(A)

np.float64(-11.000000000000002)

### If np.linalg.det(A) == 0 that means it has no or infinite solution 
### If np.linalg.det(A) is (not=0) that means it has solution 

In [39]:
d = np.linalg.det(A)
print(f"The determinant of A is: {d:.2f}")  ## .2f means there will be two decimal number.

The determinant of A is: -11.00


In [44]:
A = np.array([[-1,3],[3,2]])
b = np.array([7,1])
A.shape,b.shape

((2, 2), (2,))

In [45]:
b = b.reshape(2,1)

In [46]:
b.shape

(2, 1)

In [49]:
## To see the whole eqation as a matrix we need to horizontally stack it 
aug_mat = np.hstack((A,b))
aug_mat[0], aug_mat[1]

(array([-1,  3,  7]), array([3, 2, 1]))

In [50]:
aug_mat_copy = aug_mat.copy()
aug_mat_copy

array([[-1,  3,  7],
       [ 3,  2,  1]])

In [51]:
aug_mat_copy[1] = aug_mat_copy[0] * 3 + aug_mat_copy[1]
aug_mat_copy[1] = aug_mat_copy[1] / 11
aug_mat_copy

array([[-1,  3,  7],
       [ 0,  1,  2]])

#### Solving system of linear equation using Elimination Method . 
$$
\begin{cases}
-x_1 + 3x_2 = 7 , \\
3x_1 + 2x_2 = 1
\end{cases}
$$

In [54]:
## We can see on aug_mat_new[1] : 0x1 + 1x2 = 2 , that means x2 = 2 , 
## now we can just implement x2 on any array to get the x1
x_2 = aug_mat_copy[1,2]
x_2

np.int64(2)

In [55]:
# So x_1 is : implementing the x_2 value onto the first equation 
x_1 = 3*x_2 - 7
x_1

np.int64(-1)

In [57]:
print(f"Answer of x1 and x2 is:{x_1},{x_2}")

Answer of x1 and x2 is:-1,2
