In [2]:
import numpy as np 
import matplotlib.pyplot as plt

### This Equation 
$$
\begin{cases}
-x_1+3x_2 = 7, \\
3x_1+2x_2 = 1
\end{cases}
$$

### Representing and Solving System of Linear Equations using Matrices

In [31]:
A = np.array([[-1,3],[3,2]],dtype = int)
b = np.array([7,1],dtype = int)
x = np.linalg.solve(A,b)
x

array([-1.,  2.])

In [32]:
det_A = np.linalg.det(A)
print(f"Determinant of A is: {det_A:.2f}")

Determinant of A is: -11.00


In [44]:
# check if answer is correct
x1 , x2 = x
check1 = -1*x1 + 3*x2
check2 = 3*x1 + 2*x2
print(f"x1:{check1}")
print(f"x2:{check2}")

x1:7.0
x2:1.0


### Solving System of Linear Equations using Elimination Method

In [45]:
aug_mat = np.hstack((A,b.reshape(2,1)))
aug_mat

array([[-1,  3,  7],
       [ 3,  2,  1]])

In [46]:
aug_mat_new = aug_mat.copy()
aug_mat_new[0],aug_mat_new[1]

(array([-1,  3,  7]), array([3, 2, 1]))

In [47]:
aug_mat_new[1] = aug_mat_new[0] * 3 + aug_mat_new[1]
aug_mat_new[1] = aug_mat_new[1]/11
aug_mat_new

array([[-1,  3,  7],
       [ 0,  1,  2]])

### This Equation 
$$
\begin{cases}
-x_1+3x_2 = 7, \\
3x_1+2x_2 = 1
\end{cases}
$$

In [52]:
# -x1 + 3x2 = 7 , x2 = 2 , now just eliminate 
x2 = aug_mat_new[1,2]
x1 = (2*x2 - 1) / 3
print(f"Answer Of X1 & X2 is: {x1},{x2}")

Answer Of X1 & X2 is: 1.0,2


## Graphical Representation of the Solution  